[package]
name = "increment"
version = "0.1.0"
authors = ["Michael Shustin <michael.shustin@vastdata.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
